customRules:
  falco_rules.local.yaml: |-
    - macro: user_known_contact_k8s_api_server_activities
      condition: or container.name contains "grafana-sc-"
      override:
        condition: append

    - list: authorized_outbound_images
      items: [
        "docker.io/rancher/mirrored-coredns-coredns",
        "docker.io/cloudflare/cloudflared",
        "quay.io/prometheus/alertmanager",
        "docker.io/grafana/grafana",
        "docker.io/grafana/tempo",
        "docker.io/rancher/mirrored-library-traefik",
        "docker.io/otel/opentelemetry-collector-k8s",
        "quay.io/kiwigrid/k8s-sidecar",
        "registry.k8s.io/kube-state-metrics/kube-state-metrics",
        "quay.io/prometheus-operator/prometheus-operator",
        "quay.io/prometheus/node-exporter",
        "quay.io/prometheus/prometheus",
        "docker.io/kaka750/finflow-backend"
      ]

    - list: authorized_shell_images
      items: [
        "docker.io/kaka750/falco-receiver"
      ]

    - rule: global-shell-exec-detection
      desc: Detect shell execution inside any production container
      condition: >
        spawned_process
        and proc.name in (bash, sh, zsh, busybox)
        and container
        and not container.image.repository in (authorized_shell_images)
      output: >
        Unauthorized terminal shell detected |
        process=%proc.name cmd=%proc.cmdline container=%container.name image=%container.image.repository
      priority: CRITICAL
      tags: [security, k8s, rbi-compliance]

    - rule: outbound-rule-no-unauthorized-traffic
      desc: Outbound traffic detected from unauthorized container
      condition: >
        outbound
        and container
        and not container.image.repository in (authorized_outbound_images)
      output: >
        Unauthorized container outbound network detected |
        connection=%fd.name process=%proc.name image=%container.image.repository
      priority: WARNING

falco:
  json_output: true
  http_output:
    enabled: true
    url: http://falcosidekick.monitoring.svc.cluster.local:2801

falcosidekick:
  enabled: true
  config:
    webhook:
      address: "http://falco-receiver-svc.monitoring.svc.cluster.local:3000/alert"
      minimumpriority: "notice"