customRules:
  falco_rules.local.yaml: |-
    - macro: user_known_contact_k8s_api_server_activities
      condition: or container.name contains "k8s_grafana-sc"
      override:
        condition: append
