{
 "title": "FinFlow Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "API Transactions Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "97210c96", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "finflow-backend" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [
        "request handler - /api/transactions"
       ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "FinFlow — CPU Usage (per pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"finflow\", pod=~\"finflow.*\"}[5m])) by (pod)"
    }
   ]
  },
  {
   "title": "FinFlow — Pod Restarts (last 5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"finflow\", pod=~\"finflow.*\"}[5m])"
    }
   ]
  },
  {
   "title": "FinFlow — CPU % of Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"finflow\", pod=~\"finflow.*\"}[5m])) / sum(kube_pod_container_resource_limits{namespace=\"finflow\", pod=~\"finflow.*\", resource=\"cpu\"}) * 100"
    }
   ]
  },
  {
   "title": "FinFlow — Memory Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"finflow\", pod=~\"finflow.*\"} / 1024 / 1024"
    }
   ]
  },
  {
   "title": "FinFlow — Pod Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=\"finflow\", pod=~\"finflow.*\"}"
    }
   ]
  },
  {
   "title": "FinFlow — Memory % of Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"finflow\", pod=~\"finflow.*\"}) / sum(kube_pod_container_resource_limits{namespace=\"finflow\",pod=~\"finflow.*\",resource=\"memory\"}) * 100"
    }
   ]
  }
 ]
}