apiVersion: apps/v1
kind: Deployment
metadata:
  name: falco-receiver
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: falco-receiver
  template:
    metadata:
      labels:
        app: falco-receiver
    spec:
      serviceAccountName: falco-receiver-sa
      containers:
        - name: falco-receiver
          image: kaka750/falco-receiver:v10.1-arm
          ports:
            - containerPort: 3000
          env:
           - name: CLIENT_NAME
             value: "XYZ Payments Pvt Ltd"
           - name: CLIENT_RBI_NO
             value: "RBI-PA-2024-XXXX"
           - name: CLIENT_DOMAIN
             value: "xyzpayments.in"
           - name: CISO_NAME           # ← NEW
             value: "Rajesh Kumar"
           - name: CISO_DESIGNATION    # ← NEW
             value: "Chief Information Security Officer"
          volumeMounts:
            - name: data
              mountPath: /data
          resources: 
            requests:
               cpu: 50m
               memory: 64Mi
            limits:
               cpu: 200m
               memory: 128Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: falco-receiver-pvc
