apiVersion: apps/v1
kind: Deployment 
metadata: 
 name: finflow-frontend
spec: 
  selector:
   matchLabels:
     app: finflow-frontend
  template:
    metadata:
     labels:
       app: finflow-frontend
    spec:
     serviceAccountName: svc-acc-frontend
     containers:
     - name: finflow-frontend
       image: kaka750/finflow-frontend:v1
       resources:
         requests:
           cpu: 100m
       readinessProbe:
         httpGet:
           path: '/'
           port: 80
         initialDelaySeconds: 10
       livenessProbe:
         httpGet:
           path: '/'
           port: 80
         initialDelaySeconds: 30
       ports:
        - containerPort: 80
