apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: finflow-backend
  namespace: finflow
spec:
  selector:
   matchLabels:
    app: finflow-backend
  template:
   metadata:
    labels:
     app: finflow-backend
   spec:
    containers:
       - name: finflow-backend
         image: kaka750/finflow-backend:v5-arm
         livenessProbe:
           httpGet:
            path: '/health'
            port: 5000
           initialDelaySeconds: 30
         readinessProbe:
            httpGet:
             path: '/health'
             port: 5000 
            initialDelaySeconds: 10
         ports:
           - containerPort: 5000
         envFrom:
          - configMapRef:
              name: postgres-config
          - secretRef:
              name: postgres-secrets
         resources:
           requests:
             cpu: 100m
             memory: 30Mi
           limits:
             cpu: 300m
             memory: 60Mi
