apiVersion: apps/v1
kind: Deployment 
metadata: 
 name: finflow-frontend
 namespace: finflow
spec: 
  selector:
   matchLabels:
     app: finflow-frontend
  template:
    metadata:
     labels:
       app: finflow-frontend
    spec:
    
     containers:
     - name: finflow-frontend
       image: kaka750/finflow-frontend:v5-arm
       resources:
         requests:
           cpu: 100m
           memory: 100Mi
         limits:
           cpu: 300m
           memory: 300Mi
       readinessProbe:
         httpGet:
           path: '/'
           port: 80
         initialDelaySeconds: 10
       livenessProbe:
         httpGet:
           path: '/'
           port: 80
         initialDelaySeconds: 30
       ports:
        - containerPort: 80
