apiVersion: v1
kind: Service 
metadata: 
 name: finflow-frontend-svc
 namespace: finflow
spec:
   type: ClusterIP
   selector:
     app: finflow-frontend
   ports:
    - port: 80
      targetPort: 80
