server {
    listen 80;
    server_name localhost;

    # Gzip Compression (Page load speed fast karne ke liye)
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;

        # Security Headers (CISO Flex)
        add_header X-Frame-Options "DENY";
        add_header X-Content-Type-Options "nosniff";
        add_header X-XSS-Protection "1; mode=block";
       add_header Content-Security-Policy "
        default-src 'self';
        script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com https://unpkg.com;
        style-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com https://fonts.googleapis.com;
        font-src 'self' https://fonts.gstatic.com;
        img-src 'self' data:;
        connect-src 'self' https://demo.kartikinfra.in https://alerts.kartikinfra.in;
      " always;
    }

    # Error pages
    error_page 404 /index.html;
}
