apiVersion: batch/v1 
kind: CronJob 
metadata:
 name: pg-backup-cronjob
spec:
 schedule: "*/2 * * * *"
 jobTemplate:
   spec:
    template: 
      spec:
        volumes:
         - name: pg-backup-cronjob 
           persistentVolumeClaim:
            claimName: pg-backup
           
        restartPolicy: "OnFailure"
        containers:
          - name: postgres-backup 
            image: postgres
            command: ["/bin/sh", "-c"] 
            args: ["pg_dump -U finflow_user -d finflow -h postgres-svc > /backup/backup-$(date +%Y%m%d-%H%M%S).sql"]
            env:
             - name: PGPASSWORD
               valueFrom:
                 secretKeyRef:
                   name: postgres-secrets
                   key: POSTGRES_PASSWORD 

            volumeMounts:
             - name: pg-backup-cronjob 
               mountPath: /backup/

               

