apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc-acc-backend
  namespace: finflow

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc-acc-frontend
  namespace: finflow

---

apiVersion: v1
kind: ServiceAccount
metadata: 
  name: svc-acc-postgres
  namespace: finflow
